# Generated by Django 6.1.1 on 2026-09-11 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.TextField(help_text='The prayer request details')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('answered', 'Answered'), ('closed', 'Closed')], default='pending', max_length=10)),
                ('date_submitted', models.DateField(auto_now_add=True)),
                ('date_answered', models.DateField(blank=True, null=True)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('member', models.ForeignKey(help_text='The member this prayer request is for', on_delete=django.db.models.deletion.CASCADE, related_name='prayer_requests', to='members.member')),
            ],
            options={
                'verbose_name': 'Prayer Request',
                'verbose_name_plural': 'Prayer Requests',
                'ordering': ['-date_submitted'],
            },
        ),
    ]
