# Generated by Django 6.1.1 on 2026-09-12 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_prayerrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Singing, Piano, Teaching Children, Ushering', max_length=150)),
                ('category', models.CharField(choices=[('music', 'Music & Worship'), ('teaching', 'Teaching & Preaching'), ('ushering', 'Ushering & Hospitality'), ('media', 'Media & Technology'), ('children', 'Children & Youth'), ('administration', 'Administration & Finance'), ('outreach', 'Evangelism & Outreach'), ('prayer', 'Prayer & Intercession'), ('helps', 'Helps & Practical Service'), ('other', 'Other')], default='other', max_length=20)),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=15)),
                ('is_available_for_ministry', models.BooleanField(default=True, help_text='Is this member willing to serve in this area?')),
                ('notes', models.TextField(blank=True)),
                ('recorded_on', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(help_text='The member with this talent', on_delete=django.db.models.deletion.CASCADE, related_name='talents', to='members.member')),
            ],
            options={
                'verbose_name': 'Talent',
                'verbose_name_plural': 'Talents',
                'ordering': ['member__last_name', 'name'],
            },
        ),
    ]
