# Generated by Django 6.1.1 on 2026-09-14 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_talent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.AddField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to mark as inactive (soft delete)'),
        ),
        migrations.AddField(
            model_name='member',
            name='member_id',
            field=models.CharField(blank=True, help_text='Auto-generated on save (e.g., ZBC-2026-0001)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='organ',
            field=models.CharField(blank=True, choices=[('men', "Men's Fellowship"), ('women', "Women's Fellowship"), ('youth', 'Youth Fellowship')], help_text='The fellowship group this member belongs to', max_length=10),
        ),
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, help_text='Passport-size or 4x4 photo', null=True, upload_to='member_photos/'),
        ),
        migrations.AddField(
            model_name='member',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spouse_name', models.CharField(blank=True, help_text='Full name of spouse', max_length=200)),
                ('wedding_anniversary', models.DateField(blank=True, help_text='Optional — date of wedding', null=True)),
                ('notes', models.TextField(blank=True)),
                ('member', models.OneToOneField(help_text='The member this family belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='family', to='members.member')),
            ],
            options={
                'verbose_name': 'Family',
                'verbose_name_plural': 'Families',
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='members.family')),
            ],
            options={
                'verbose_name': 'Child',
                'verbose_name_plural': 'Children',
                'ordering': ['date_of_birth'],
            },
        ),
    ]
