# Generated by Django 6.1.1 on 2026-09-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_options_member_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.CharField(blank=True, help_text='Auto-generated on save (e.g., ZBC-2026-0001)', max_length=20, unique=True),
        ),
    ]
